version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etudiants
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
